// Lugar Nacimiento: "Este, Sur, Oeste, Norte, Grand Line, Otro, Desconocido"
// Ocupacion: "Pirata, Marine, Revolucionario, Capitan, Navegante"
// Especie: "Humano, Animal, Gyojin, Desconocido"
// Fruta Diablo: "Paramencia, Logia, Zoan, No tiene, Desconocido"

const state = {
    "unknow": "Desconocida",
    "no": "No tiene",
    "caballero": "Shichibukai",
    "para": "Paramecia",
    "realeza": "Realeza",
    "pre": "Zoan Prehistórica"
}

const data = {
    "personajes": [
        // EAST BLUE SAGA
        {
            "id": 1,
            "label": "Luffy",
            "imagen": "https://avatars.pfptown.com/585/luffy-pfp-1651.png",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "East Blue",
            "fruta": "Zoan",
            "recompensa": 3000065000,
            "edad": 19,
            "ocupacion": ["Capitan", "Pirata", "Emperador"],
            "aparicion": 1999
        },
        {
            "id": 2,
            "label": "Zoro",
            "imagen": "https://wallpapers-clan.com/wp-content/uploads/2022/08/zoro-pfp-1.jpg",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "East Blue",
            "fruta": "No tiene",
            "recompensa": 1111000000,
            "edad": 21,
            "ocupacion": ["Espadachin", "Comandante", "Pirata"],
            "aparicion": 1999
        },
        {
            "id": 4,
            "label": "Nami",
            "imagen": "https://www.dreamtavern.ai/_next/image?url=https%3A%2F%2Frizz-public-assets.s3.us-west-2.amazonaws.com%2Fimages%2F8c117b47-b46a-484e-927a-b7ff639f6a79.png&w=640&q=75",
            "genero": "Femenino",
            "especie": "Humano",
            "blue": "East Blue",
            "Fruta": "No tiene",
            "recompensa": 366000000,
            "edad": 20,
            "ocupacion": ["Pirata", "Navegante"],
            "aparicion": 1999,
        },
        {
            "id": 11,
            "label": "Shanks",
            "imagen": "shanks.jpg",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "West Blue",
            "fruta": "No tiene",
            "recompensa": 4048900000,
            "edad": 39,
            "ocupacion": ["Pirata", "Capitán", "Emperador"],
            "aparicion": 1999
        },
        {
            "id": 7,
            "label": "Sanji",
            "imagen": "https://i.pinimg.com/originals/3d/0d/97/3d0d9744c192ff7d905a863d0ef335ae.gif",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "North Blue",
            "fruta": "No tiene",
            "recompensa": 1032000000,
            "edad": 21,
            "ocupacion": ["Pirata", "Cocinero"],
            "aparicion": 2000
        },
        {
            "id": 8,
            "label": "Usopp",
            "imagen": "https://i.pinimg.com/originals/5e/ae/15/5eae152bfdb0078c8f97f18c7dbfc886.jpg",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "East Blue",
            "fruta": "No tiene",
            "recompensa": 500000000,
            "edad": 19,
            "ocupacion": ["Pirata", "Tirador"],
            "aparicion": 1999
        },
        {
            "id": 12,
            "label": "Roger",
            "imagen": "https://64.media.tumblr.com/fd0d1ded6938d0da548df108fe028d8c/e373942f3b7c9833-b9/s400x600/3dc5a987f32302251c42b0605f335387efabd66e.gif",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "East Blue",
            "fruta": "No tiene",
            "recompensa": 5564800000,
            "edad": 53,
            "ocupacion": ["Pirata", "Capitán", "REY"],
            "aparicion": 1999
        },
        {
            "id": 15,
            "label": "Dragon",
            "imagen": "https://i.pinimg.com/originals/cc/e5/ca/cce5ca7c6957c4694ab7fe30b0cdcf6e.jpg",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "East Blue",
            "fruta": state.unknow,
            "recompensa": state.unknow,
            "edad": 55,
            "ocupacion": ["Revolucionario"],
            "aparicion": 2000
        },
        {
            "id": 27,
            "label": "Buggy",
            "imagen": "https://i.pinimg.com/originals/38/1a/eb/381aeb3ece63f397508d78e2011ba52c.jpg",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "East Blue",
            "fruta": state.para,
            "recompensa": 3189000000,
            "edad": 39,
            "ocupacion": ["Pirata", "Capitán", "Emperador"],
            "aparicion": 1999
        },
        {
            "id": 33,
            "label": "Makino",
            "imagen": "https://i.pinimg.com/1200x/e1/a0/14/e1a014de149bf0c906c617b710cea07f.jpg",
            "genero": "Femenino",
            "especie": "Humano",
            "blue": "East Blue",
            "fruta": state.no,
            "recompensa": state.no,
            "edad": 31,
            "ocupacion": ["Civil"],
            "aparicion": 1999
        },
        {
            "id": 34,
            "label": "Higuma",
            "imagen": "https://static.wikia.nocookie.net/onepiece/images/e/e2/Higuma_Anime_Infobox.png",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "East Blue",
            "fruta": state.no,
            "recompensa": 8000000,
            "edad": 46,
            "ocupacion": ["Bandido"],
            "aparicion": 1999
        },
        {
            "id": 35,
            "label": "Beckman",
            "imagen": "https://i.pinimg.com/originals/a4/e3/c3/a4e3c32d5c37b64a5e3a91851df2e573.jpg",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "North Blue",
            "fruta": state.no,
            "recompensa": state.unknow,
            "edad": 50,
            "ocupacion": ["Pirata", "Comandante"],
            "aparicion": 1999
        },
        {
            "id": 36,
            "label": "Alvida",
            "imagen": "https://pm1.aminoapps.com/6353/249690aa4a78c20d41b74e3ad142ce21b84f8c02_hq.jpg",
            "genero": "Femenino",
            "especie": "Humano",
            "blue": "East Blue",
            "fruta": state.para,
            "recompensa": 5000000,
            "edad": 27,
            "ocupacion": ["Pirata", "Capitan"],
            "aparicion": 1999
        },
        {
            "id": 37,
            "label": "Morgan",
            "imagen": "https://static.wikia.nocookie.net/onepiece/images/e/e5/Morgan_Anime_Infobox.png",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "East Blue",
            "fruta": state.no,
            "recompensa": state.no,
            "edad": 44,
            "ocupacion": ["Marine"],
            "aparicion": 1999
        },
        {
            "id": 39,
            "label": "Koby",
            "imagen": "https://i.pinimg.com/736x/fc/b2/01/fcb20184f88cc57d534e7043d48825ee.jpg",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "East Blue",
            "fruta": state.no,
            "recompensa": state.no,
            "edad": 18,
            "ocupacion": ["Marine", "Comodoro"],
            "aparicion": 1999
        },
        {
            "id": 40,
            "label": "Helmeppo",
            "imagen": "https://static.wikia.nocookie.net/onepiece/images/6/6c/Helmeppo_Before_Training_Portrait.png",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "East Blue",
            "fruta": state.no,
            "recompensa": state.no,
            "edad": 22,
            "ocupacion": ["Marine"],
            "aparicion": 1999
        },
        {
            "id": 41,
            "label": "Kuina",
            "imagen": "https://static.wikia.nocookie.net/onepiece/images/c/c1/Shimotsuki_Kuina_Anime_Infobox.png",
            "genero": "Femenino",
            "especie": "Humano",
            "blue": "East Blue",
            "fruta": state.no,
            "recompensa": state.no,
            "edad": 11,
            "ocupacion": ["Espadachin"],
            "aparicion": 1999
        },
        {
            "id": 42,
            "label": "Kuro",
            "imagen": "https://media.tenor.com/Dp3-z-7qSNIAAAAM/one-piece-kuro.gif",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "East Blue",
            "fruta": state.no,
            "recompensa": 16000000,
            "edad": 35,
            "ocupacion": ["Pirata", "Capitan", "Bandido"],
            "aparicion": 2000
        },
        {
            "id": 43,
            "label": "Jango",
            "imagen": "https://static.wikia.nocookie.net/onepiece/images/d/de/Jango_Anime_Infobox.png/",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "East Blue",
            "fruta": state.no,
            "recompensa": state.no,
            "edad": 29,
            "ocupacion": ["Marine"],
            "aparicion": 2000
        },
        {
            "id": 44,
            "label": "Kaya",
            "imagen": "https://i.pinimg.com/736x/7b/f4/9b/7bf49b5bfc895967de889edd06df0b2e.jpg",
            "genero": "Femenino",
            "especie": "Humano",
            "blue": "East Blue",
            "fruta": state.no,
            "recompensa": state.no,
            "edad": 19,
            "ocupacion": ["Civil", "Medico"],
            "aparicion": 2000
        },
        {
            "id": 45,
            "label": "Krieg",
            "imagen": "https://static.wikia.nocookie.net/onepiece/images/b/bb/Krieg_Anime_Infobox.png",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "East Blue",
            "fruta": state.no,
            "recompensa": 17000000,
            "edad": 44,
            "ocupacion": ["Pirata", "Capitan"],
            "aparicion": 2000
        },
        {
            "id": 46,
            "label": "Zeff",
            "imagen": "https://static.wikia.nocookie.net/onepiece/images/d/d9/Zeff_Anime_Infobox.png",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "East Blue",
            "fruta": state.no,
            "recompensa": state.unknow,
            "edad": 67,
            "ocupacion": ["Cocinero"],
            "aparicion": 2000
        },
        {
            "id": 47,
            "label": "Mihawk",
            "imagen": "https://i.pinimg.com/originals/28/d3/1d/28d31dde9df6ae8e3fa28ae5c21b2d7e.jpg",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": state.unknow,
            "fruta": state.no,
            "recompensa": 3590000000,
            "edad": 43,
            "ocupacion": ["Pirata", "Espadachin", state.caballero],
            "aparicion": 2000
        },
        {
            "id": 48,
            "label": "Arlong",
            "imagen": "https://s4.anilist.co/file/anilistcdn/character/large/b4887-hMOqSSpR5jFc.jpg",
            "genero": "Masculino",
            "especie": "Gyojin",
            "blue": "Grand Line",
            "fruta": state.no,
            "recompensa": 20000000,
            "edad": 41,
            "ocupacion": ["Capitan", "Pirata"],
            "aparicion": 2000
        },
        {
            "id": 49,
            "label": "Hatchan",
            "imagen": "https://i.pinimg.com/564x/04/64/30/0464306a26c7a4be2376b1257ffbcec7.jpg",
            "genero": "Masculino",
            "especie": "Gyojin",
            "blue": "Grand Line",
            "fruta": state.no,
            "recompensa": 8000000,
            "edad": 38,
            "ocupacion": ["Pirata", "Cocinero"],
            "aparicion": 2000
        },
        {
            "id": 50,
            "label": "Smoker",
            "imagen": "https://i.pinimg.com/originals/c0/c6/8b/c0c68b64584b2dd9381d248e6a4c4d46.gif",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "Grand Line",
            "fruta": "Logia",
            "recompensa": state.no,
            "edad": 36,
            "ocupacion": ["Marine", "Vicealmirante"],
            "aparicion": 2000
        },
        {
            "id": 51,
            "label": "Tashigi",
            "imagen": "https://static.wikia.nocookie.net/saintpirates/images/4/4d/Tashigi.png",
            "genero": "Femenino",
            "especie": "Humano",
            "blue": "East Blue",
            "fruta": state.no,
            "recompensa": state.no,
            "edad": 23,
            "ocupacion": ["Marine", "Comodoro", "Espadachin"],
            "aparicion": 2000
        },
        //////////////////////////////////
        // Saga Arabasta
        {
            "id": 38,
            "label": "Crocus",
            "imagen": "https://www.nautiljon.com/images/perso/00/00/crocus_200.webp",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "Grand Line",
            "fruta": state.no,
            "recompensa": state.unknow,
            "edad": 73,
            "ocupacion": ["Pirata", "Medico"],
            "aparicion": 2001
        },
        {
            "id": 6,
            "label": "Brook",
            "imagen": "https://i.pinimg.com/originals/2e/4c/7b/2e4c7be1dc0ef9d0f578a9c27877af0a.gif",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "West Blue",
            "fruta": state.para,
            "recompensa": 383000000,
            "edad": 90,
            "ocupacion": ["Pirata", "Musico", "Espadachin"],
            "aparicion": 2008
        },           
        {
            "id": 3,
            "label": "Chopper",
            "imagen": "https://static.wikia.nocookie.net/fiveworldadventures/images/6/66/Tony_Tony_Chopper.png",
            "genero": "Masculino",
            "especie": "Animal",
            "blue": "Grand Line",
            "fruta": "Zoan",
            "recompensa": 1000,
            "edad": 17,
            "ocupacion": ["Pirata", "Medico"],
            "aparicion": 2001
        },
        {
            "id": 9,
            "label": "Robin",
            "imagen": "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/c2a4fd09-561a-4019-b2c9-6461fa3db151/denkmme-fe44e66d-4842-49db-bac9-980f928b10eb.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcL2MyYTRmZDA5LTU2MWEtNDAxOS1iMmM5LTY0NjFmYTNkYjE1MVwvZGVua21tZS1mZTQ0ZTY2ZC00ODQyLTQ5ZGItYmFjOS05ODBmOTI4YjEwZWIuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.C1kulNJq3N14FAJdWSplXJnQtVKeiLveeOHSTwE9cJ4",
            "genero": "Femenino",
            "especie": "Humana",
            "blue": "West Blue",
            "fruta": state.para,
            "recompensa": 930000000,
            "edad": 30,
            "ocupacion": ["Pirata"],
            "aparicion": 2001
        },
        {
            "id": 10,
            "label": "Kid",
            "imagen": "https://i.pinimg.com/736x/dd/7c/bd/dd7cbdcd5b45576f6080e793f9a00ec1.jpg",
            "genero": "Masculino",
            "especie": ["Humano", "Cyborg"],
            "blue": "South Blue",
            "fruta": state.para,
            "recompensa": 3000000000,
            "edad": 23,
            "ocupacion": ["Pirata", "Capitán"],
            "aparicion": 2009
        },
        {
            "id": 5,
            "label": "Jinbe",
            "imagen": "https://pbs.twimg.com/media/FYXlrhkUEAAEoXb.jpg",
            "genero": "Masculino",
            "especie": "Gyojin",
            "blue": "Grand Line",
            "fruta": "No Tiene",
            "recompensa": 1100000000,
            "edad": 46,
            "ocupacion": ["Pirata", state.caballero],
            "aparicion": 2009
        },      
        {
            "id": 13,
            "label": "Xebec",
            "imagen": "https://i.pinimg.com/474x/47/ea/5a/47ea5aa7ec2d716bb2acb1af07759377.jpg",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": state.unknow,
            "fruta": state.no,
            "recompensa": state.unknow,
            "edad": state.unknow,
            "ocupacion": ["Pirata", "Capitán"],
            "aparicion": 2021
        },
        {
            "id": 14,
            "label": "Garp",
            "imagen": "https://i.pinimg.com/564x/37/db/81/37db8155f82e1d23c82d31b25e0bfc73.jpg",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "East Blue",
            "fruta": "No tiene",
            "recompensa": state.no,
            "edad": 78,
            "ocupacion": ["Marine", "Vicealmirante"],
            "aparicion": 2001
        },      
        {
            "id": 16,
            "label": "Franky",
            "imagen": "https://static.wikia.nocookie.net/onepiece-fairytail/images/3/35/Franky.png",
            "genero": "Masculino",
            "especie": ["Humano", "Cyborg"],
            "blue": "South Blue",
            "fruta": "No tiene",
            "recompensa": 394000000,
            "edad": 36,
            "ocupacion": ["Pirata"],
            "aparicion": 2005
        },
        {
            "id": 16,
            "label": "Sabo",
            "imagen": "https://i.pinimg.com/originals/b8/3e/55/b83e5589d93653272885beaefd11651c.jpg",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "East Blue",
            "fruta": "Logia",
            "recompensa": 602000000,
            "edad": 22,
            "ocupacion": ["Revolucionario"],
            "aparicion": 2011
        },
        {
            "id": 17,
            "label": "Ace",
            "imagen": "https://i.pinimg.com/736x/63/df/d2/63dfd2a0a58e98b6cd1d4f21b6cd15d2.jpg",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "South Blue",
            "fruta": "Logia",
            "recompensa": 550000000,
            "edad": 20,
            "ocupacion": ["Pirata", "Comandante"],
            "aparicion": 2001
        },
        {
            "id": 18,
            "label": "Vivi",
            "imagen": "https://i.pinimg.com/originals/03/69/ee/0369eee9afe3587e90704d834be0a889.jpg",
            "genero": "Femenino",
            "especie": "Humano",
            "blue": "Grand Line",
            "fruta": state.no,
            "recompensa": state.no,
            "edad": 18,
            "ocupacion": [state.realeza],
            "aparicion": 1999
        },
        {
            "id": 19,
            "label": "Katakuri",
            "imagen": "https://i.pinimg.com/originals/40/10/f7/4010f77fc43fa928f82e27361ef21fe4.jpg",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "Grand Line",
            "fruta": state.para,
            "recompensa": 1057000000,
            "edad": 48,
            "ocupacion": ["Pirata", "Comandante"],
            "aparicion": 2018
        },
        {
            "id": 20,
            "label": "Kaido",
            "imagen": "https://i.pinimg.com/736x/6d/4b/38/6d4b381f2a5d7ae710651a834fff150f.jpg",
            "genero": "Masculino",
            "especie": "Oni",
            "blue": "Grand Line",
            "fruta": "Zoan Mitica",
            "recompensa": 4600000000,
            "edad": 59,
            "ocupacion": ["Pirata", "Capitan", "Emperador"],
            "aparicion": 2016
        },
        {
            "id": 21,
            "label": "Yamato",
            "imagen": "https://i.redd.it/zu9qc9lu0f9b1.jpg",
            "genero": "Femenino",
            "especie": "Oni",
            "blue": "Grand Line",
            "fruta": "Zoan Mitica",
            "recompensa": state.no,
            "edad": 28,
            "ocupacion": ["Pirata"],
            "aparicion": 2021
        },
        {
            "id": 22,
            "label": "King",
            "imagen": "https://i.pinimg.com/736x/57/cd/82/57cd825fb6e0e2dd9a295b778ed96f8d.jpg",
            "genero": "Masculino",
            "especie": "Lunaria",
            "blue": "Grand Line",
            "fruta": state.pre,
            "recompensa": 1390000000,
            "edad": 47,
            "ocupacion": ["Pirata", "Comandante", "Espadachin"],
            "aparicion": 2019
        },
        {
            "id": 23,
            "label": "Big Mom",
            "imagen": "https://i.pinimg.com/736x/f8/3f/f2/f83ff2840617e00da4c9e803acb7944c.jpg",
            "genero": "Femenino",
            "especie": "Humano",
            "blue": "Grand Line",
            "fruta": state.para,
            "recompensa": 4700000000,
            "edad": 68,
            "ocupacion": ["Pirata", "Capitan", "Emperador"],
            "aparicion": 2012
        },
        {
            "id": 24,
            "label": "Barbablanca",
            "imagen": "https://pm1.aminoapps.com/6349/cd23e9e89864019927c77063141b86a5c061352d_00.jpg",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "Grand Line",
            "fruta": state.para,
            "recompensa": 5046000000,
            "edad": 72,
            "ocupacion": ["Pirata", "Capitán"],
            "aparicion": 2003
        },
        {
            "id": 25,
            "label": "Marco",
            "imagen": "https://i.pinimg.com/1200x/d2/48/63/d248632c7db52b197fd4ccae1981f0a0.jpg",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "Grand Line",
            "fruta": "Zoan Mitica",
            "recompensa": 1374000000,
            "edad": 45,
            "ocupacion": ["Pirata", "Comandante", "Medico"],
            "aparicion": 2003
        },
        {
            "id": 26,
            "label": "Barbanegra",
            "imagen": "https://static.wikia.nocookie.net/saintpirates/images/d/d0/Marshall_D._Teach.png",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "Grand Line",
            "fruta": "Logia",
            "recompensa": 3996000000,
            "edad": 40,
            "ocupacion": ["Pirata", "Capitán", "Emperador"],
            "aparicion": 2003
        },
        
        {
            "id": 28,
            "label": "Cobra",
            "imagen": "https://static.wikia.nocookie.net/onepiece/images/6/6d/Nefertari_Cobra_Anime_Pre_Timeskip_Infobox.png",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "Grand Line",
            "fruta": state.no,
            "recompensa": state.no,
            "edad": 50,
            "ocupacion": ["Realeza"],
            "aparicion": 2001
        },
        {
            "id": 29,
            "label": "Neptune",
            "imagen": "https://static.wikia.nocookie.net/onepiece/images/4/40/Neptune_Anime_Infobox.png",
            "genero": "Masculino",
            "especie": "Tritón",
            "blue": "Grand Line",
            "fruta": state.no,
            "recompensa": state.no,
            "edad": 70,
            "ocupacion": ["Realeza"],
            "aparicion": 2012
        },
        {
            "id": 30,
            "label": "Shirahoshi",
            "imagen": "https://i.pinimg.com/564x/2d/81/03/2d81035f3f30461024dca37726522d70.jpg",
            "genero": "Femenino",
            "especie": "Sirena",
            "blue": "Grand Line",
            "fruta": state.no,
            "recompensa": state.no,
            "edad": 16,
            "ocupacion": ["Realeza"],
            "aparicion": 2012
        },
        {
            "id": 31,
            "label": "Judge",
            "imagen": "https://static.wikia.nocookie.net/onepiece/images/6/6f/Vinsmoke_Judge_Anime_Infobox.png",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "North Blue",
            "fruta": state.no,
            "recompensa": state.no,
            "edad": 56,
            "ocupacion": ["Realeza", "Cientifico"],
            "aparicion": 2017
        },
        {
            "id": 32,
            "label": "Ryuma",
            "imagen": "https://static.wikia.nocookie.net/onepiece/images/6/6a/Shimotsuki_Ryuma_Anime_Infobox.png",
            "genero": "Masculino",
            "especie": "Humano",
            "blue": "Grand Line",
            "fruta": state.no,
            "recompensa": state.no,
            "edad": 47,
            "ocupacion": ["Samurai", "Espadachin"],
            "aparicion": 2008
        }

    ]
}

export default data